NEW = 0
WHOLE_CHANGE = 1
UNCHANGED = 2
DATE_CHANGE = 3
STRUCTURE_CHANGE = 4
DELETE = 5
ORDER_RECORD_STATUS_CHOICES = (
	(NEW,'NEW'),
	(WHOLE_CHANGE,'WHOLE_CHANGE'),
	(UNCHANGED,'UNCHANGED'),
	(DATE_CHANGE,'DATE_CHANGE'),
	(STRUCTURE_CHANGE,'STRUCTURE_CHANGE'),
	(DELETE,'DELETE'),
)

# title
STATUS_TITLE_CHOICES = (
	(NEW,'신규'),
	(WHOLE_CHANGE,'변경'),
	(UNCHANGED,'미 변경'),
	(DATE_CHANGE,'출하 일자 변경'),
	(STRUCTURE_CHANGE,'설계 변경'),
	(DELETE,'삭제'),
)



